presubmits:
- name: pull-Pi-build
  always_run: true
  decorate: true
  path_alias: github.com/cnrseng/Pi
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    - image: gcc
      securityContext:
        privileged: true
      command:
      - sleep
      args:
      - "50"
