presubmits:
- name: pull-Pi-build
  always_run: true
  decorate: true
  path_alias: github.com/cnrseng/Pi
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    - image: registry.redhat.io/codeready-workspaces/stacks-cpp-rhel8:2.14-9
      securityContext:
        privileged: true
      command:
      - g++
      args:
      - "-fopenmp"
      - "pi.c"
      - "-o"
      - "pi"
